### ISSUE TITLE
Question about the LICENSE

### ISSUE THREAD

**Issue by ArjixWasTaken** [LilithWittmann/jugendschutzprogramm#3]
This is a funny topic, since this is merely an API wrapper for a single endpoint.

Personally I wouldn't give the LICENSE any importance since well, as I said, this ain't much.

But I do question the legality of licencing reverse-engineered code, or well, disassembled code.

The token generation part of the code could be considered something non-generic, so I'd assume it is protected by the copyright holder, in this case JusProg.

How are you applying a licence on-top of that? And what measures do you have to protect your licence?

Since well, applying a licence means you are declaring ownership of the code...

Unless you just picked a template that came with a LICENSE already chosen for you.

**Comment by ArjixWasTaken** [comment]
For reference:

I like reverse engineering games and such, and I always make sure to not publish disassembled code and variations of it to play it safe.

So I am surprised a variation of the disassembled function is not only published, but it is under an open source licence.

I ain't here to cause trouble or anything like that, I'm just a curious mind.

**Comment by ArjixWasTaken** [comment]
On another note, it may be possible to generate the token w/o writing an implementation of the code.

E.g. by extracting the class from the apk file and using a java VM.

**Comment by LilithWittmann** [comment]
This is not disassembled code, but code written by myself. I just checked the general principles on how the android implementation works.

Creating a hash value and taking the first n chars is such generic, that I don't worry about copyright. So it is my code which I can license to you. I really see no issues - from a copyright perspective.

**Comment by LilithWittmann** [comment]
Well actually I double checked: I did not write the code. Copilot did. I just described the method 🤪.

**Comment by ArjixWasTaken** [comment]
Lol
